apiVersion: v1
kind: Service
metadata:
  name: mongodb-external-service
spec:
  type: ExternalName
  # 동일 노드 내 다른 Docker 컨테이너라면 보통 호스트의 사설 IP를 적어줍니다.
  externalName: 172.17.0.1 # Docker Bridge의 호스트 IP 예시